### PR TITLE
Removed slime block

### PR DESCRIPTION
**Pull request by ribagi**

### CODE REVIEW

**Comment by Lazersmoke** [comment]
why?

**Comment by Ameliorate** [comment]
This removes the per-chunk limit on slime blocks, not their recipe.

**Comment by Lazersmoke** [comment]
Yes, but why? Presumably there was some sort of breaking balance and/or lag issue with slime blocks to warrant their ban in the first place. Has that concern been otherwise addressed, or were they just put in with the rest because they are a technical block?

**Comment by ribagi** [comment]
Oh forgot to close this. There was an issue resolved another way.

**Pull request closed without merging**
