### PR TITLE
remove custom "Manna" cookie name to prepare for MemeMana

### PR DESCRIPTION
**Pull request by Gjum**

### CODE REVIEW

**Comment by Lazersmoke** [comment]
This PR should be made to `1.12-changes`. Resolves #35.

**Comment by Gjum** [comment]
you meant resolves #33, and it only works if teal says the magic words ;)

**Comment by Lazersmoke** [comment]
Ah yeah, wrong number haha, and you need write access to do the magic :P

**Comment by Lazersmoke** [comment]
@TealNerd this is OK to merge here, unless you want to rename the cookies something new

**Pull request merged**
