### PR TITLE
Reorganised, congrete, and compressor

### PR DESCRIPTION
**Pull request by ghost**
Re-organised the config as to make it more readable as on many occasions recipes for the same factory were scattered randomly throughout the file.

 * Removed the duplicate "upgrade_to_intermediate_cauldron" and "upgrade_to_advanced_cauldron", keeping the one present in game

 * Change the prices of mixing concrete to what you said in this post: https://redd.it/7nx4ov ("64 concrete powder with 1 dye, 16 gravel, and 16 sand.")

 * Implemented my idea of a Compressor as described here: https://redd.it/8di2yw

It should work out of the box, but may require some testing, if only to see if the numbers are balanced.

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Imo the compression idea is largely problematic not only due to the coal being absurdly common, but it is also a resource dropped from mobs (Wither Skeletons), thus making it a renewable resource. Going forward with that idea would basically enable afkable diamonds.  

Not to mention also concrete costs were reduced in PR #44 although I think it is currently double the rates your PR proposes

**Comment by ghost** [comment]
Ah, the price is so high because of how common coal is. It seemed to me that a stack of coal blocks for a single diamond would be about right, but then again I'm not too involved with the economy which is why I recommended playing around with the price to see what works right.

As for the Wither Skeletons, I... was not actually aware of that, TIL. It wouldn't be hard to set the amount of coal they drop to zero, if it came down to that. Or the resource could be changed to fossils? I don't know, this was just an idea to solve, or at least partially fix the issues with the current ore spawning, plus introducing another method of generating diamonds without spending hours underground.

Either way, if the Compressor idea is a no go, at least for now, may the commit go through if I comment it out/remove it? This commit still has the re-organisation and concrete price changes

----

Edit: Yeah, the concrete prices were lowered to match vanilla prices for sand and gravel. But you're still trading needing four less dye for charcoal and durability. Not exactly the kind of trade expected for factories, nor was it the one promised to us.

**Comment by Diet-Cola** [comment]
One change I would suggest is to change the output of the compressor to lets say, Lored Light blue glass.(This is so people don't craft an actual diamond into a block to remove the lore and then craft the block back into diamonds).
Double check the durability to ensure its light blue otherwise we're gonna have funky synth diamonds.
```
Synth Diamond:
        material: STAINED_GLASS
        durability: 3
        amount: 1
        lore:
        - Synthesized Diamond
```

Then I would simply change the diamond armour and tool factories to accept these synth diamonds on a 3x scaled input cost. Therefore armour and tools can get back into the circulation of the game however raw diamond can be saved purely for repair materials and reinforcement. 

I would consult @ribagi or @TealNerd first however to see if they would accept these temporary changes.

**Comment by ribagi** [comment]
I can't even tell what you did because of the reordering

**Comment by ghost** [comment]
It might be better to look at the file rather that the commit itself. [View here.](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml)

The order goes as follow:

 * Factories

 * Upgrades

 * Recipes

The ordering within those sections is based on the [list of upgrades on the Dirt! baseline factory](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml#L29) at the top of the file. The only thing that breaks this is the upgrades to basic intermediate and advanced cauldron, they are listed together in the upgrades section, not in the recipes of their respective predecessors. (Just for the file though, nothing has been changed in-game, except for the actual changes to the config listed below:)

 * [Changed each concrete recipe to cost 1 dye, 16 sand, and 16 gravel.](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml#L5077)

 * [Added an upgrade recipe to the Dirt! baseline factory for the Compressor](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml#L62)

 * [Defined the Compressor factory itself and what recipes it has, including moving the Pack Ice recipe from Aesthetics to the Compressor.](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml#L678)

 * [And lastly, defined the Compressor recipes themselves.](https://github.com/Cranite/Configs/blob/b4a2eeedb1a20f16445653857b81f3c8e9bef75e/FactoryMod/config.yml#L5411)

Because of the organisation, it's easy to find things that are meant to be together.

**Pull request closed without merging**
