### PR TITLE
Make the logging snitch cull value dependent on the non-logging one

### PR DESCRIPTION
**Pull request by awoo-civ**
It's better this way, trust me.

### CODE REVIEW

**Comment by TealNerd** [comment]
Why should it be double?

**Comment by Maxopoly** [comment]
It's easier to explain and remember, makes more sense with jukes being way more expensive and 'syncs' the intervalls in which you have to refresh your snitches. Instead of having to go out every 42 days to only do jukes or do all your jukes and notes every 14 days you can do notes every 2 weeks and get them as well on your juke tour every 4 weeks.

**Comment by awoo-civ** [comment]
Pretty much what Max said, it's a bit hard to explain but here goes.

Right now, since the Juke cull time is only 1.5x that of Notes, their update times are not synced. Say you build a snitch grid where you start using Jukes instead of Notes as snitches get farther away than distance x so that you don't have to refresh those as often.

Refreshing right now:
1. Refresh the Notes 2 weeks from now.
2. Refresh the Jukes 3 weeks from now.
3. Refresh the Notes 4 weeks from now.
4. Refresh the Notes + Jukes 6 weeks from now.
5. Refresh the Notes 8 weeks from now.

After the change:
 1. Refresh the Notes 2 weeks from now.
2. Refresh the Notes + Jukes 4 weeks from now.
3. Refresh the Notes 6 weeks from now.
4. Refresh the Notes + Jukes 8 weeks from now.

It makes sense from a balance perspective - you get to refresh less often at a rather high price of having to use Jukes.

**Comment by awoo-civ** [comment]
@TealNerd any decision?

**Pull request merged**
