### PR TITLE
Add acid blocks

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

**Comment by TealNerd** [comment]
why

**Comment by Diet-Cola** [comment]
https://www.reddit.com/r/civclassics/comments/7i2i1c/fix_pvp_so_the_war_ends/dqw5wsm/

**Comment by TealNerd** [comment]
What does that have to do with acid blocks though, they're usually pretty easy to see anyway

**Comment by Peter5930** [comment]
@TealNerd  The reason is that acid blocks are used in traps and those traps are reportedly being rendered ineffective by people x-raying them and spotting the gold blocks under the surface.  Gold blocks under a layer of sand are not usually pretty easy to see unless you have x-ray.

**Pull request closed without merging**
